version: "3.8"
services:
    # app:
    #     build: .
    #     ports:
    #         - 4000:4000
    #     depends_on:
    #         - postgres

    postgres:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgres
